# Site settings
title: Chris Mytton
email: chrismytton@gmail.com
description: I'm a Developer at mySociety. This is my personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.chrismytton.uk" # the base hostname & protocol for your site
username: chrismytton

# Build settings
markdown: kramdown
permalink: pretty
timezone: Europe/London
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-paginate
exclude: [README.md, CNAME, Gemfile, Gemfile.lock]

# Plugin settings
feed:
  path: index.xml
twitter:
  username: chrismytton
author:
  name: Chris Mytton
  twitter: chrismytton
lang: en_GB
paginate: 7
