# Site settings
title: Chris Mytton
email: chrismytton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the blog of Chris Mytton, a Developer living in Bristol who
  spends his days building awesome websites, apps and tools.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.chrismytton.uk" # the base hostname & protocol for your site
twitter_username: chrismytton
github_username: chrismytton
google_analytics_code: UA-58688654-1

# Build settings
markdown: kramdown
permalink: pretty
timezone: Europe/London
exclude: ['Gemfile', 'Gemfile.lock', 'deploy']

gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
