# Site settings
title: Chris Mytton
email: chrismytton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Developer at mySociety, currently working on EveryPolitician. This is my personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.chrismytton.uk" # the base hostname & protocol for your site
# twitter_username: chrismytton
github_username: chrismytton
google_analytics_code: UA-58688654-1

# Build settings
markdown: kramdown
permalink: pretty
timezone: Europe/London
exclude:
  - Gemfile
  - Gemfile.lock
  - deploy
  - s3_website.yml
  - .gitlab-ci.yml
